name: Build And Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-musleabihf
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out -rs project
        uses: actions/checkout@v2
        with:
          repository: zhimin-dev/iptv-checker-rs
          path: iptv-checker-rs

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cross
        if: matrix.os == 'ubuntu-latest'
        run: cd iptv-checker-rs && cargo install cross

      - name: Build - windows
        if: matrix.os == 'windows-latest'
        run: cd iptv-checker-rs &&  cargo build --release --target ${{ matrix.target }}

      - name: Build - linux
        if: matrix.os == 'ubuntu-latest'
        run: cd iptv-checker-rs &&  cross build --release --target ${{ matrix.target }}

      - name: Build - macos
        if: matrix.os == 'macos-latest'
        run: cd iptv-checker-rs &&  cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: cd iptv-checker-rs &&  strip "target/${{ matrix.target }}/release/iptv-checker-rs"

      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          cd iptv-checker-rs
          binary_name="iptv-checker-rs"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
