name: Desktop

on:
  push:
    tags:
      - "d*"
  workflow_dispatch: # or just on button clicked

permissions:
  contents: write

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Checkout iptv-checker-web
        uses: actions/checkout@v4
        with:
          repository: zhimin-dev/iptv-checker-web
          path: iptv-checker-web

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: install app dependencies and build it
        working-directory: ./iptv-checker-web
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: 'App v${{ env.VERSION }}'
          releaseBody: 'See the assets to download this version and install.'

      - name: Build archive
        shell: bash
        working-directory: ./iptv-checker-web
        run: |
          binary_name="iptv-checker-desktop"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv "src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg" "$dirname"
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            mv "src-tauri/target/${{ matrix.target }}/release/bundle/deb/*.deb" "$dirname"
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "src-tauri/target/${{ matrix.target }}/release/bundle/nsis/*.exe" "$dirname"
          fi
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./iptv-checker-web/${{ env.ASSET }}
